### ISSUE TITLE
pod still refers to 1.0 client as the default one

### ISSUE THREAD

**Issue by garu** [elastic/elasticsearch-perl#100]
Hi everyone!

[This section of the documentation](https://metacpan.org/pod/Search::Elasticsearch#BACKWARDS-COMPATIBILITY-AND-ELASTICSEARCH-0.90.x) still refers to 1.0 as being the default client for Search::Elasticsearch:

*"This version of the client supports the Elasticsearch 1.0 branch by default, which is not backwards compatible with the 0.90 branch."*

*"If you need to talk to a version of Elasticsearch before 1.0.0, please use Search::Elasticsearch::Client::0_90::Direct as follows:"*

The rest of the pod looks ok, properly referencing the 2.0 client.

Hope this helps. Cheers!

**Comment by clintongormley** [comment]
HI @garu 

thanks for reporting. closed by https://github.com/elastic/elasticsearch-perl/commit/12dcdd9419546a4ec2561f7eff12de30fa75fed1
