### ISSUE TITLE
Support http_address format of Elasticsearch 2.x in Sniff connection pool

### ISSUE THREAD

**Issue by tom-mi** [elastic/elasticsearch-perl#101]
With Elasticsearch 2.x, the address format returned from the node api has changed:

    curl -s -XGET http://my-db:9200/_nodes?pretty  | grep addr
        ...
          "http_address" : "my-db/1.2.3.4:9201",
        ...

The old format was `inet[my-db/1.2.3.4:9201]`. When using a `Sniff`
connection pool, the resulting node addresses are not parsed correctly, i.e. 
the hostname is not stripped off. This yields unusable connections:

    [Cxn] ** [http://my-db:80/1.2.3.4:9201]-[599] Could not connect to 'my-db:80': Connection refused

The problem only occurs if a hostname is given, otherwise the content of `http_address` is just `<ip>:<port>` and the non-matching regex in `Role::CxnPool::Sniff` does not hurt.

**Comment by clintongormley** [comment]
thanks for reporting @tom-mi - 2.02 is now available

**Comment by tom-mi** [comment]
That was quick -- thanks :+1:
