### ISSUE TITLE
MSYS2 Perl

### ISSUE THREAD

**Issue by CharlesBunders** [elastic/elasticsearch-perl#102]
Trying to use elasticsearch-perl on windows via MSYS2. Version I have with that:

This is perl 5, version 22, subversion 0 (v5.22.0) built for i686-msys-thread-multi-64int

ES Perl uses numerous modules that are not packaged under MSYS. Downloading the tar.gz's for the dependencies I eventually hit:

~/Params-Util-1.07
$ perl Makefile.PL
In file included from sanexs-dDixE.c:2:0:
C:/msys32/usr/lib/perl5/core_perl/CORE/perl.h:805:25: fatal error: sys/wait.h: No such file or directory

For the Params module install.

Is there an elastic search perl module without such heavy dependencies on other modules? I have already had to install manually:

Data-OptList-0.110.tar.gz    
Moo-2.001001.tar.gz     
Params-Util-1.07.tar.gz           
Module-Runtime-0.014.tar.gz  
Sub-Exporter-0.987.tar.gz

None of these are packaged for MSYS2.

**Comment by clintongormley** [comment]
Sorry @CharlesBunders but this is the first time I've even heard of MSYS2.

> C:/msys32/usr/lib/perl5/core_perl/CORE/perl.h:805:25: fatal error: sys/wait.h: No such file or directory

This just looks wrong.  Not sure I'd trust MSYS2 in this case...  who knows what else is broken.

As for minimal dep elastic clients, you could try https://metacpan.org/pod/Elastijk
