### ISSUE TITLE
wrong charset 

### ISSUE THREAD

**Issue by sopov** [elastic/elasticsearch-perl#106]
Before contact with server, library make convert charset (utf8->latin1 and send as utf)
as result we can see correct result if push/get by id 
but if we make search then have wrong results.

**Comment by clintongormley** [comment]
I don't understand what you mean.  Could you provide some code that demonstrates the issue?

**Comment by sopov** [comment]
I already replace code to clean of LWP, but special for you:
see samples here here https://github.com/sopov/issues/

1. we add 1st psalm in Russian to ES (text in DATA)
code bug-of-elasticsearch-perl.cgi  log of works in bug-of-elasticsearch-perl.txt
a) we add psalm by verse to test via Search::Elasticsearch (log start with = INDEX) – all is OK
b) we return all records (= GET) – all is OK
c) make search list by uniq word from each verse ( lines 42, for you in comment add line and word position)
as you can see all return all records in different order. On my works with 10K+ records i see result without search word
d) now we add to ES data via LWP (LWP::Simple::Post + LWP::Simple, log start with = LWP) 
e) check that all is ok (= GET)
f) check search and see for each word is correct result
g) make request via curl
g1) bug-of-elasticsearch-perl.curl-se.txt -- you can see wrong charset
g2) bug-of-elasticsearch-perl.curl-se-iconv.txt -- add iconv and all is ok
g3) bug-of-elasticsearch-perl.curl-lwp.txt -- is lwp -- all is OK
commands in .sh-file

**Comment by clintongormley** [comment]
I'm still struggling to follow what you're doing, but there is an obvious problem in https://github.com/sopov/issues/blob/master/bug-of-elasticsearch-perl.cgi - you don't decode your text from utf8 before passing it to Search::Elasticsearch.

You either need to `use utf8` or `decode_utf8` your strings before using them, otherwise they aren't real perl strings, they are just utf8 bytes.

**Comment by clintongormley** [comment]
No further feedback. Closing
