### ISSUE TITLE
RFC: support x-http-method-override for non-POST/UPDATE req. with body

### ISSUE THREAD

**Issue by mickeyn** [elastic/elasticsearch-perl#107]
since we see DELETE requests sent to clear scrolled searches with HTTP body which is not always possible to get through all networking services, I suggest supporting x-http-method-override mode to allow clients to send them through POST requests.
@clintongormley, I realize this requires support on ES side, so the suggestion is for both.

@ranguard is currently debugging related issues with the new MetaCPAN setup because of this.
it may be beneficial to all in the long run.

**Comment by ranguard** [comment]
@mickeyn actually it works with the network services we have - was a misconfiguration on my part blocking it

**Comment by mickeyn** [comment]
cool. but i think it might be a good idea in any case.

**Comment by clintongormley** [comment]
@mickeyn as you say, this would need to be added to elasticsearch itself.  I suggest opening an issue there instead, along with good reasons for doing it.  My initial reaction is that it makes filtering requests harder for the sysadmin...

**Comment by mickeyn** [comment]
@clintongormley I guess this issue can be reduced (at the moment, based on what we saw) to the DELETE requests for scrolled searches which forces sending a body.
I understand the complexity of this, so a quick question - will it make more sense to ask for a URL route/query param support for these deletes?
i.e.
`curl -XDELETE localhost:9200/_search/scroll?id=c2Nhbjs2OzM0NDg1ODpzRlBLc0FXNlNyNm5JWUc1`
or
`curl -XDELETE localhost:9200/_search/scroll/c2Nhbjs2OzM0NDg1ODpzRlBLc0FXNlNyNm5JWUc1`

As far as I understand from the docs these are not supported.

If you think it's a better idea, I can open a request for that specifically instead.

**Comment by clintongormley** [comment]
@mickeyn that's a possibility.  That said, scroll IDs can be very long when targeting many shards which can make them too long for the max URL size accepted by http servers, so sending them in the body is safer.

**Comment by mickeyn** [comment]
I totally agree, but the use-case is when some http-client or network service doesn't allow you to pass a body with the DELETE... the RFC is not clear about that so some choose to discard the body or reject the request.
