### ISSUE TITLE
Failed assertions

### ISSUE THREAD

**Issue by eserte** [elastic/elasticsearch-perl#108]
On some systems the `2{0,1,2}_xs_encode_*.t` tests may fail with assertion errors. Sample reports on CPAN Testers:
- http://www.cpantesters.org/cpan/report/3d53c0be-698f-11e6-a44b-abd558b9f28c
- http://www.cpantesters.org/cpan/report/d56f96e8-3d7f-11e6-baf5-eb17d217bde1

I could reproduce such a fail also on one of my linux smokers, running perl 5.24.0.

It seems to be required for such failures to compile perl with -DDEBUGGING.

**Comment by clintongormley** [comment]
Hi @eserte 

Thanks for the heads up (and the hint about -DDEBUGGING which wouldn't have occurred to me). That looks like a problem in JSON::XS - the tests in S::Elasticsearch aren't doing anything terribly special:  https://github.com/elastic/elasticsearch-perl/blob/master/t/20_Serializer/encode_decode.pl

I'll dig into it more when i have a chance

**Comment by eserte** [comment]
Yes, I could generate the assertion failure with a single encode_json call. See https://rt.cpan.org/Ticket/Display.html?id=118280

**Comment by clintongormley** [comment]
thanks @eserte - btw, to report a bug on JSON::XS you should email Marc Lehmann directly.  See https://metacpan.org/pod/JSON::XS#BUGS

**Comment by eserte** [comment]
The bug report was also sent via email to him (via CC).

**Comment by clintongormley** [comment]
This appears to have been resolved upstream as these tests no longer fail.  Thanks for reporting.

Closing
