### ISSUE TITLE
version 5 and multiple clients

### ISSUE THREAD

**Issue by mickeyn** [elastic/elasticsearch-perl#109]
according to https://v1.metacpan.org/changes/distribution/Search-Elasticsearch
I **should** install **one** of the clients modules (for 0.x, 1.x & 2.x) - 
will it work with multiple ones? I have a client that needs to interact with different versions (0.x & 2.x) by condition (different servers) - is this possible with this version?

**Comment by clintongormley** [comment]
Hi @mickeyn 

yes it is possible.  You specify which client version you want when you instantiate the client, eg:

    $e=Search::Elasticsearch->new( client => '5_0::Direct' )
