### ISSUE TITLE
Options trace_to/log_to are shared between connections

### ISSUE THREAD

**Issue by enp** [elastic/elasticsearch-perl#115]
Hi,

I tried to use log_to with two different connections:

```
my $es_1 = Search::Elasticsearch->new(
	nodes => "10.0.0.11:9200",
	log_to => 'Stderr'
);
    
my $es_2 = Search::Elasticsearch->new(
	nodes => '10.0.0.12:9200'
);

$es_1->get(index => 'state', type => 'session', id => 0, ignore  => 404);
$es_2->get(index => 'state', type => 'session', id => 0, ignore  => 404);
```

But I see logging for both connections:

```
Current cxns: ["http://10.0.0.11:9200"]
Forcing ping before next use on all live cxns
Ping [http://10.0.0.11:9200] before next request
Current cxns: ["http://10.0.0.12:9200"]
Forcing ping before next use on all live cxns
Ping [http://10.0.0.12:9200] before next request
```

I see the same with trace_to. Is it possible to fix this?

**Comment by clintongormley** [comment]
hi @enp 

You can use the `log_as` parameter (see https://metacpan.org/pod/Search::Elasticsearch::Role::Logger#log_as) to change the `category` used for one or both of your connections, then each connection will use a different logger, eg:

    $e1 = Search::Elasticsearch->new( log_as => 'i_want_to_see_this', log_to => 'Stderr')
    $e2 = Search::Elasticsearch->new( )

Only `$e1` will show up in Stderr.
