### ISSUE TITLE
Search::Elasticsearch::Async needs a new release

### ISSUE THREAD

**Issue by robn** [elastic/elasticsearch-perl#116]
The version on CPAN has a S::E::Cxn::AEHTTP that consumes S::E::Cxn::HTTP. That role has been removed in the CPAN version of Search::Elasticsearch, so S::E::A fails:

```
$ perl -MSearch::Elasticsearch::Async -E 'Search::Elasticsearch::Async->new'
Can't locate Search/Elasticsearch/Role/Cxn/HTTP.pm in @INC (you may need to install the Search::Elasticsearch::Role::Cxn::HTTP module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /usr/share/perl5/Module/Runtime.pm line 317.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 317.
```

I see the change has been in git for some time; a new release would be greatly appreciated.

**Comment by clintongormley** [comment]
That's weird - I did release v5.0.0 but for some reason PAUSE wasn't happy with it.

See https://metacpan.org/pod/release/DRTECH/Search-Elasticsearch-Async-5.00/lib/Search/Elasticsearch/Async.pm

I had some issues when releasing 5.0.0 - I think PAUSE was struggling to keep up and didn't adjust permissions properly.  I'll try a new release shortly.

**Comment by abraxxa** [comment]
There is still something not ok regarding the CPAN index:

> [ahartmai@ahartmai-nb:~/perl5/git/NAC-Logging$ (master)]$ dzil listdeps --missing | cpanm
--> Working on Message::Passing::Output::Search::Elasticsearch
Fetching http://www.cpan.org/authors/id/A/AB/ABRAXXA/Message-Passing-Output-Search-Elasticsearch-0.003.tar.gz ... OK
Configuring Message-Passing-Output-Search-Elasticsearch-0.003 ... OK
==> Found dependencies: Search::Elasticsearch::Async
! Finding Search::Elasticsearch::Async on cpanmetadb failed.
! Finding Search::Elasticsearch::Async (5.00) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution Search::Elasticsearch::Async (5.00)
! Installing the dependencies failed: Module 'Search::Elasticsearch::Async' is not installed
! Bailing out the installation for Message-Passing-Output-Search-Elasticsearch-0.003.

**Comment by gjozef** [comment]
All other version of Search::Elasticsearch::Async then 2.03, including 5.00 are only in BackPAN. Is it  possible to release the next version? Thank you.

**Comment by clintongormley** [comment]
Sorry it's taken a while, but Search::Elasticsearch::Async should now be on 5.02.  Please let me know if you see any issues

**Comment by abraxxa** [comment]
metacpan finde 5.02 when searching for Search::Elasticsearch::Async and `cpanm --look Search::Elasticsearch::Async` downloads and unpacks the correct tarball as well, so can confirm that it's fixed.
Thanks Clinton!

**Comment by clintongormley** [comment]
@abraxxa great - thanks for letting me know, and sorry it took so long
