### ISSUE TITLE
Hard dependency on AnyEvent for ::Async

### ISSUE THREAD

**Issue by Grinnz** [elastic/elasticsearch-perl#117]
The Search-Elasticsearch-Async distribution has backends for both AnyEvent and Mojo, but has a hard dependency on AnyEvent::HTTP, AnyEvent::TLS and AE. I have a very strong aversion to introducing AnyEvent into my dependency chain, but would like to have the option to use the Mojo backend in the future. Is there any possibility of either making the AnyEvent dependencies optional like Mojolicious is, or somehow making a separate distribution that depends on Mojolicious and not AnyEvent? Or some other solution? (I also would prefer to use Future instead of Promises, as I am more confident in its functionality and interaction with Mojo::IOLoop, but I don't feel as strongly about that part.) Thanks.

**Comment by clintongormley** [comment]
Hi @Grinnz 

The reason for the hard dependency is that I need an event loop to run the tests - i just use:

    $cv = AE::cv;
    # do something
    $cv->recv

I don't have the time to go figure out how to do the equivalent in Mojo and to make the required changes, but if you're up for sending a PR, I'd be happy to help you work through it

Regarding Futures, I looked at the two modules when I wrote the Async version, and preferred the Promises API (and spent quite a lot of time bringing that module up to spec).  That said, it should be pretty easy to build a wrapper that converts Promises to Futures.  Again, if you're interested in doing the legwork, I'd be happy to help you.

**Comment by clintongormley** [comment]
No further feedback. Closing
