### ISSUE TITLE
Bulk indexing fails silently when run from threaded code.

### ISSUE THREAD

**Issue by rrothwell** [elastic/elasticsearch-perl#118]
Following the standard recipe for bulk indexing, when the ES submission code is run from multiple Perl threads, it produces no traffic on the wire. No error messages are produced.
Forcing a flush produces an empty items array as the response.

When the same submission code is executed outside a thread it runs perfectly.

Similarly a call to $bulk_endpoint->cluster->health fails, but that does produce error messages.

This indexing code worked perfectly satisfactorily with the previous version of the Search::Elasticsearch, however that code is no longer visible on CPAN. 

Could the old code be restored, until the new code is fixed please?

**Comment by clintongormley** [comment]
Hi @rrothwell 

I'm afraid I've never used Perl with threading and have no idea where to start. I also doubt that any of the HTTP backends are thread safe.  I'm not going to go back to code in (which version?), but I'll accept patches which help to make Search::Elasticsearch work with threads.

**Comment by clintongormley** [comment]
No further feedback. Closing
