### ISSUE TITLE
Scroll IDs expected as JSON

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch-perl#122]
Now that Elasticsearch no longer does content-type detection, a plain text scroll ID body no longer works.

Scrolls just pass a body like:

    { scroll_id => $scroll_id }

**Comment by Grinnz** [comment]
This still doesn't seem to work correctly for a DELETE request. This shows up in my log when using the scroll helper, it's triggered from the destructor so it doesn't seem to cause code issues but the scroll ID probably hangs around longer than it needs to.

```
[Thu May 25 13:04:21 2017] [Request] ** [http://aws-nv-dev-es-001.ventusdev.com:9200]-[400] [illegal_argument_exception] Unknown parameter [scroll_id] in request body or parameter is of the wrong type[VALUE_STRING] , called from sub modified(Search::Elasticsearch::Client::5_0::Role::Scroll::DEMOLISH) at (eval 619) line 21. With vars:
{'request' => {'path' => '/_search/scroll','serialize' => 'std','mime_type' => 'application/json','qs' => {},'ignore' => [],
'body' => {'scroll_id' => 'DnF1ZXJ5VGhlbkZldGNoBQAAAAAAf8frFkM4QXdOb3NHUnZTbUhhdFhIUHdxNEEAAAAAAH_H7BZDOEF3Tm9zR1J2U21IYXRYSFB3cTRBAAAAAAB_x-8WQzhBd05vc0dSdlNtSGF0WEhQd3E0QQAAAAAAf8ftFkM4QXdOb3NHUnZTbUhhdFhIUHdxNEEAAAAAAH_H7hZDOEF3Tm9zR1J2U21IYXRYSFB3cTRB'},
'method' => 'DELETE'},
'body' => {'error' => {'type' => 'illegal_argument_exception','root_cause' => [{'type' => 'illegal_argument_exception','reason' => 'Unknown parameter [scroll_id] in request body or parameter is of the wrong type[VALUE_STRING] '}],'reason' => 'Unknown parameter [scroll_id] in request body or parameter is of the wrong type[VALUE_STRING] '},'status' => 400},'status_code' => 400}```

**Comment by clintongormley** [comment]
Yeah, they have to be passed as an array until ES v5.5.0 is released https://github.com/elastic/elasticsearch/pull/24242

**Comment by Grinnz** [comment]
Would it make sense for Search::Elasticsearch to always pass it in an array? I believe the spot triggering my errors is at https://github.com/elastic/elasticsearch-perl/blob/master/lib/Search/Elasticsearch/Client/5_0/Scroll.pm#L112

**Comment by Grinnz** [comment]
https://github.com/elastic/elasticsearch-perl/blob/master/lib/Search/Elasticsearch/Client/5_0/Async/Scroll.pm#L194 also looks like it would be affected by this for those using the async client.
