### ISSUE TITLE
delete_by_query and parameter wait_for_completion

### ISSUE THREAD

**Issue by jordivador** [elastic/elasticsearch-perl#129]
In cpan documentation I see that's not supported via perl client `wait_for_completion` as delete_by_query  parameter but Elasticsearch does allow it .

Also I've tried it , for in the case lack info in documentation but the response was: 

``` 
([Param] ** Unknown param (wait_for_completion)
```

https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-delete-by-query.html

There's any reason to not allow `delete_by_query` with `wait_for_completion=false` ? 

Thanks!

Update:

I see that's implemented for Search::Elasticsearch for version >5.0 , but not implemented for Search::Elasticsearch 2.03

**Comment by clintongormley** [comment]
Delete-by-query used a different mechanism in 2.x so wait_for_completion wasn't available in that release
