### ISSUE TITLE
put_script() defaults to mustache

### ISSUE THREAD

**Issue by A80qWEHg** [elastic/elasticsearch-perl#132]
Since 6.0 I have issues with stored scripts. The lang is set to "mustache" and therefore ES can't interpret them correctly. Also the resulting stored script is not always the same ?!
 
```perl
#!/usr/bin/perl -w
use strict; 
use Search::Elasticsearch 6.0;

my $e = Search::Elasticsearch->new;

# according to the documentation the lang defaults to painless
# --> https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html

$e->put_script(
    id   => 'test',
    body => { 
        lang => 'painless',
        source => q(return), 
    },
);

print `curl -s localhost:9200/_scripts/test?pretty`;
```
By running this script multiple times I get two different outputs in random order:

```json
{
  "_id" : "test",
  "found" : true,
  "script" : {
    "lang" : "mustache",
    "source" : "{\"source\":\"return\"}"
  }
}
```

```json
{
  "_id" : "test",
  "found" : true,
  "script" : {
    "lang" : "mustache",
    "source" : "{\"lang\":\"painless\"}"
  }
}
```
Strange stuff!

> This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux
> Version: 6.0.0, Build: 8f0685b/2017-11-10T18:41:22.859Z, JVM: 1.8.0_152

**Comment by clintongormley** [comment]
There are two issues here.  First, you're using the wrong syntax, use this instead:

```
$e->put_script(
    id   => 'test',
    body => { 
        script => {
            lang => 'painless',
            source => q(return)
        }
    }
);
```

And second, a bug in Elasticsearch that it is accepting this malformed request. I have opened https://github.com/elastic/elasticsearch/issues/27612 to get that fixed.

**Comment by A80qWEHg** [comment]
Thank you very much for your time and advice. Maybe you can update the example in [https://metacpan.org/pod/Search::Elasticsearch::Client::6_0::Direct#put_script()](https://metacpan.org/pod/Search::Elasticsearch::Client::6_0::Direct#put_script()) as well?
That would be awesome.

**Comment by clintongormley** [comment]
Ah thanks for pointing that out. I've pushed a fix
