### ISSUE TITLE
Cannot connect over IPv6

### ISSUE THREAD

**Issue by gregf1** [elastic/elasticsearch-perl#135]
When attempting to connect over IPv6
```
my $e = Search::Elasticsearch->new(
    port        => 9200,
    nodes       => ['2001:db8:85a3::8a2e:370:7334']
);
```
I get the following error:
> No nodes are available: [http://2001:db8:85a3::8a2e:370:7334:80]

The problem is in Search::Elasticsearch::Role::Cxn

Firstly, the port is incorrectly set to '80' because of this:
```
if ( $params->{port} && $node !~ m{//[^/]+:\d+} ) {
    $node =~ s{(//[^/]+)}{$1:$params->{port}};
}
```
The node regex is wrong - it incorrectly thinks there is already a port when there isn't.

Secondly, the IP address is not put in brackets both in this line
```
$node =~ s{(//[^/]+)}{$1:$params->{port}};
```
and this line
```
$params->{uri} = URI->new("$scheme://$host:$port$path");
```

To fix the port issue you probably want to do something like
```
    unless ( ref $node eq 'HASH' ) {
        $node = "[$node]" if Net::IP::ip_is_ipv6($node);
        unless ( $node =~ m{^http(s)?://} ) {
            $node = ( $params->{use_https} ? 'https://' : 'http://' ) . $node;
        }
        if ( $params->{port} && $node !~ m{//[^/\[]+:\d+} ) {
            $node =~ s{(//[^/]+)}{$1:$params->{port}};
        }
```
ie
```
+ $node = "[$node]" if Net::IP::ip_is_ipv6($node);
```
```
- if ( $params->{port} && $node !~ m{//[^/]+:\d+} ) {
+ if ( $params->{port} && $node !~ m{//[^/\[]+:\d+} ) {
```
And something similar for `$params->{uri}`
```
$host = "[$host]" if Net::IP::ip_is_ipv6($host);
```

**Comment by clintongormley** [comment]
Hi @gregf1 

Thanks for opening.   You want to send a PR and add the appropriate tests?  I don't know much about ipv6.
