### ISSUE TITLE
Numeric formats in cat api

### ISSUE THREAD

**Issue by morjo** [elastic/elasticsearch-perl#152]
Hi

Was wondering if you could add options for changing the numeric formats(time,size,bytes) cat api.

[Elasticsearch Cat API's](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/cat.html#numeric-formats)

**Comment by clintongormley** [comment]
Where are they missing?  The API is autogenerated from the [rest spec](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api) so if they're missing in the Perl client, then they need to be added to the spec.

**Comment by morjo** [comment]
From what I see
cat.shards is missing: time
cat.indices is missing: time
cat.nodes is missing: bytes and time

**Comment by clintongormley** [comment]
OK - could you open an issue in the elasticsearch repo - that's the place to get it fixed.

thanks
