### ISSUE TITLE
Searching with "-d @query.json" as body

### ISSUE THREAD

**Issue by brostad** [elastic/elasticsearch-perl#153]
When testing a new index mapping I often rely on some fixed queries stored in json files in a test folder, running commands like the following:

`curl -XGET "http://stage1:9200/myindex/_search" -d @test/3.json -H "Content-Type: application/json"`

Now I consider scripting this in perl but haven't been able to locate anything in the Search API that allows me to specify a file (-d @query.json) as body. Are file based queries not supported by Search::Elasticsearch?

**Comment by clintongormley** [comment]
They're not.  I don't think I'd want to add eg accepting a file handle or another parameter to check for, as I think this isn't the common use case.  The `body` parameter does however accept text instead of an object, so you could just do something like this:

```
$result = $es->search(body => from_file('my_search.json'))

sub from_file {
    local $/;
    open my $fh, '<:utf8', $_ or die $!;
    return <$fh>
}
```
