### ISSUE TITLE
Does Search::Elasticsearch support the operator => 'AND'? 

### ISSUE THREAD

**Issue by createdanew** [elastic/elasticsearch-perl#158]
**Search::Elasticsearch is up to date (6.00).** is being used 

I don't understand why my curl query logic does not work in the Search::Elasticsearch module. I'm not sure if this is a bug or perhaps I'm not properly understanding how the Search::Elasticsearch  works. 

Curl Query:  This works just fine 

root@fll-lpiek:/opt/oss/mako/bin# curl -k -XGET 'https://username:password@x.x.x.x:443/logs-2018.09.26/logs/_search?pretty=1' -d '
> {
>    "size": 1,
>    "query": {
>     "bool": {
>       "must": [
>         { "match": { "logsource": "x.x.x.x" } },
>         { "match": {"message": { "query": "ROUTING-BGP-5-ADJCHANGE_DETAIL", "operator": "and"}}},
>         {"range" : {"@timestamp" : {"gte" : "2018-09-26T20:00:00.000Z"}}}
>       ]
>     }
>   }
> }
> '

RETURNS:

{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 12,
    "max_score" : 17.532366,
    "hits" : [
      {
        "_index" : "logs-2018.09.26",
        "_type" : "logs",
        "_id" : "AWYYUgOp3wQlamheqS8x",
        "_score" : 17.532366,
        "_source" : {
          "@timestamp" : "2018-09-26T23:58:40.001Z",
          "@version" : "1",
          "host" : "x.x.x.x",
          "message" : [
            "<189>Sep 26 23:58:40 x.x.x.x RP/0/RSP0/CPU0:Sep 26 23:58:39.993 GMT: bgp[1050]: %ROUTING-BGP-5-ADJCHANGE_DETAIL : neighbor x.x.x.x Up (VRF: default; AFI/SAFI: 1/1) (AS: 14222) \n",
            "RP/0/RSP0/CPU0:Sep 26 23:58:39.993 GMT: bgp[1050]: %ROUTING-BGP-5-ADJCHANGE_DETAIL : neighbor x.x.x.x Up (VRF: default; AFI/SAFI: 1/1) (AS: 14222) \n"
          ],
          "logsource" : "x.x.x.x",
          "timestamp" : "Sep 26 23:58:40"
        }
      }
    ]
  }
}

Using 

Code Snippet: 

eval {
        alarm $timeout;
        foreach my $string (@$search_string) {
            push @$result, $es->search(
                index => $device_index,
                type =>  $search_index,
                body  => {
                    query => {
                        bool => {
                            must => [
                                 {match => {logsource   => $ip}},
                                 {match => {message => {query => $string, operator => 'AND'}}},
                                 {range => {"\@timestamp" => {gte => "2018-09-26T20:00:00.000Z"}}},
                            ],
                        }
                    },
                    size => $num_records
                }
            );
            alarm 0;
        }
    };

RETURNS:

# Request to: https://x.x.x.x:443
curl -H "Content-type: application/json" -XGET 'http://localhost:9200/logs-2018.09.26/logs/_search?pretty=1' -d '
{
   "query" : {
      "bool" : {
         "must" : [
            {
               "match" : {
                  "logsource" : "x.x.x.x"
               }
            },
            {
               "match" : {
                  "message" : {
                     "query" : "BGP-5-ADJCHANGE",
                     "operator" : "AND"
                  }
               }
            },
            {
               "range" : {
                  "@timestamp" : {
                     "gte" : "2018-09-26T20:00:00.000Z"
                  }
               }
            }
         ]
      }
   },
   "size" : 1
}
'

# Response: 200, Took: 114 ms
# {
#    "_shards" : {
#       "total" : 5,
#       "failed" : 0,
#       "successful" : 5
#    },
#    "timed_out" : false,
#    "hits" : {
#       "hits" : [],
#       "total" : 0,
#       "max_score" : null
#    },
#    "took" : 1
# }

$VAR1 = [
          {
            '_shards' => {
                           'total' => 5,
                           'failed' => 0,
                           'successful' => 5
                         },
            'timed_out' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' ),
            'hits' => {
                        'hits' => [],
                        'total' => 0,
                        'max_score' => undef
                      },
            'took' => 1
          }
        ];

Could someone help me understand if perhaps this is a bug or maybe I'm just wrong?  When I remove the operator => 'AND' I get data back and if I change the operator => 'AND' to operator => 'OR' I get data back. However, when changing it to operator => 'OR' I don't get the exact data that I want.

**Comment by clintongormley** [comment]
@createdanew This isn't the right forum for this question.  Try discuss.elastic.co instead.  You could start by running your query through the validate API to understand the actual query being run:
https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-explain.html
