### ISSUE TITLE
Problems with timeouts during create / delete of snapshots

### ISSUE THREAD

**Issue by morjo** [elastic/elasticsearch-perl#163]
We are using the 6.0 client and 6.6 of ES

If the snapshot->create is using more than 30 sec we get a timeout, event with "wait_for_completion".
 
my $create_status = $es->snapshot->create(
   repository => $respository_name,
   snapshot => $snapshot_name,
   wait_for_completion => "true",
   );

Also the trace logging that shows the curl with "pretty=1" something that is illegal.

We also get a timeout during delete, but much faster.

**Comment by clintongormley** [comment]
You're probably running into the default `request_timeout`.  See https://metacpan.org/pod/Search::Elasticsearch::Role::Cxn#request_timeout
