### ISSUE TITLE
Missing < in pod

### ISSUE THREAD

**Issue by djzort** [elastic/elasticsearch-perl#170]
https://github.com/elastic/elasticsearch-perl/blob/60f6190d68fc3460b68f5af0a0b541dca05180de/lib/Search/Elasticsearch/Client/6_0/Direct.pm#L1012

Should be C<terminate_after>

**Comment by djzort** [comment]
Hopefully you dont want a PR? :)

**Comment by clintongormley** [comment]
Thanks @djzort - I'm working on an update to 7.0 and have included that fix
