### ISSUE TITLE
Support for custom HTTP headers

### ISSUE THREAD

**Issue by philkra** [elastic/elasticsearch-perl#186]
It would great if the client could emit a custom HTTP header with every request. Two options should be available to register such a header: as global option and on a per-request basis.

**Comment by Skeeve** [comment]
Did you try 

```
$e = Search::Elasticsearch->new(
    nodes       => [ 'search1', 'search2' ],
    default_headers => {
        'X-Opaque-Id' => $id,
    },
)
```

?
