### ISSUE TITLE
$es->indices->exists_template() doesn't support "include_type_name"

### ISSUE THREAD

**Issue by truj** [elastic/elasticsearch-perl#192]
Thanks for fixing #169, which allows using the parameter **include_type_name** in **$es->indices->exists()**.
But now we have the same issue with **$es->indices->exists_template()**.
Please fix it there as well.

Background:
We try to fix our deprecation warnings before upgrading to ES 7.
Currently we use ES 6, and we get these warnings.

**exists_template()** is mapped to a HEAD request to **/_template/...**
But without include_type_name we get a warning:

```
curl -XHEAD -i -I "http://user:password@our-es-host:9201/_template/test/?pretty=true"

HTTP/1.1 404 Not Found
Server: nginx/1.10.3
Date: Wed, 22 Jul 2020 13:24:02 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 4
Connection: keep-alive
X-Opaque-Id: 10.35.150.25:37264
Warning: 299 Elasticsearch-6.7.2-56c6e48 "[types removal] The parameter include_type_name should be explicitly specified in get template requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions."
```
With this parameter the warning vanishes:
```
curl -XHEAD -i -I "http://user:password@our-es-host:9201/_template/test/?pretty=true&include_type_name=false"

HTTP/1.1 404 Not Found
Server: nginx/1.10.3
Date: Wed, 22 Jul 2020 13:23:37 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 4
Connection: keep-alive
X-Opaque-Id: 10.35.150.25:37245
```
Alternatively you can consider fixing #171.
Then this issue would be fixed automatically, and maybe other similar problems as well.

**Comment by ezimuel** [comment]
We just released https://github.com/elastic/elasticsearch-perl/releases/tag/version_7.30_1 supporting **Elasticsearch 7.3 APIs**. Please check this version and let me know if this solve the issue. Thanks!

**Comment by truj** [comment]
Meanwhile we upgraded to ES 6.8.11 on our test system.
Tried 7.30_1 with this but our unit tests fail.
Seems like 7.30_1 is only working with ES 7.X but not ES 6.X

Is this the expected behaviour?

If yes, I have to wait until everything is switched to 6.8.11. Then we can switch the test system to 7.X, and then I can test 7.30_1.
If not, I will have to check deeper, why the tests are failing with 7.30_1. (With 6.81 they are successful, apart from the not-yet-fixed deprecation warnings.)

**Comment by ezimuel** [comment]
@truj elasticsearch-perl `7.30_1` works only for ES `7.x` (up to `7.3`). This is the expected behaviour. If you want to use ES `6.x` with elasticsearch-perl `7.30_1` you need to specify `6_0::Direct` parameter in the `Search::Elasticsearch` constructor:
```perl
use Search::Elasticsearch;
my $e = Search::Elasticsearch->new(
    client => '6_0::Direct'
);
```
Basically, the `7.30_1` version includes all the previous APIs for ES `6.x`. I'm going to remove the support to the previous version 5.x, 2.x, 1.x and 0.x, see #193.
