### ISSUE TITLE
Renaming the Perl module

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch-perl#20]
In September 2013 I released the official Perl client: [`Elasticsearch.pm`](https://metacpan.org/pod/Elasticsearch) and deprecated my old client which was called [`ElasticSearch.pm`](https://metacpan.org/pod/ElasticSearch) (note the capital `S`).

At the time I was under the impression that PAUSE was case-sensitive and thought that the similarity of the names might cause a small human problem but wouldn't be a technical problem. Shortly after release, @karenetheridge pointed out to me (https://github.com/elasticsearch/elasticsearch-perl/issues/5) that users of case insensitive filesystems (Windows and OSX) would be unable to install both versions of the module at the same time, making migration problematic.

I then released [Elasticsearch::Compat](https://metacpan.org/pod/Elasticsearch::Compat), which provides the old API but uses the new Elasticsearch.pm client internally, hoping that this would ease migration.  However, there are a number of modules that depend on the old client and so conflicts continue to occur.  This issue was raised again last week in https://github.com/elasticsearch/elasticsearch-perl/issues/18.

All of the official clients are named `Elasticsearch` so I was loathe to change the name, but after talking the problem through with the cool headed @neilbowers (++), he convinced me of the need to:

1. Deprecate both `ElasticSearch.pm` and `Elasticsearch.pm` and,
2. To release the official client under a new name with no possibility of clashes.

This will cause some pain (for which I apologise) to users who have already migrated to the new `Elasticsearch.pm` as they will need to update their code to use the new name, but it is the better long term solution.

## What should it be called?

I would like feedback from users of the module as to what the new name should be.  Suggestions so far include `Search::Elasticsearch` and `Elasticsearch::V2`.  Any other suggestions are welcome. Please vote for your preferred name in the comments below.

See the [blogpost](http://www.elasticsearch.org/blog/renaming-perl-client/) for more details about the future plans for [`elasticsearch-perl`](https://github.com/elasticsearch/elasticsearch-perl/).

**Comment by ranguard** [comment]
Time to rename again... Elastic::Stuff :) ?

https://www.elastic.co/about/press/elasticsearch-changes-name-to-elastic-to-reflect-wide-adoption-beyond-search

**Comment by clintongormley** [comment]
Nooooooooooooooo

**Comment by ranguard** [comment]
You could probably close this issue then  ;)

**Comment by robinsmidsrod** [comment]
Actually, it's just the company that has changed name to "Elastic", the database/search backend is still called Elasticsearch (from reading the press release and looking at their product list on elastic.co.

**Comment by ranguard** [comment]
@robinsmidsrod yea, I knew that.. but wasn't so funny :)

**Comment by garu** [comment]
Hi @clintongormley! As @ranguard pointed out, shouldn't this issue be closed?

**Comment by clintongormley** [comment]
Indeed - I've deleted the various old variations of module names, leaving only Search::Elasticsearch::*
