### ISSUE TITLE
prereq Log::Any::Adapter:Callback is deprecated

### ISSUE THREAD

**Issue by Tux** [elastic/elasticsearch-perl#201]
other than me not wanting to install deprecated modules, I have a global red flag on modules from PERLANCAR, because it might drag in half of CPAN or useless duplications of other good modules.

Please make this prereq optional

**Comment by karenetheridge** [comment]
Log::Any::Adapter::Callback's documentation says:

> DEPRECATION NOTICE: Log::Any distribution since 1.708 comes with Log::Any::Adapter::Capture which does the same thing. I'm deprecating this adapter now.

..so it should be straightforward to switch.

**Comment by ezimuel** [comment]
@Tux thanks for reporting this and @karenetheridge thanks for the alternative proposal. I just checked `Log::Any::Adapter::Capture` and we need to refactor `t/lib/LogCallback.pl` that actually is as follows:
```perl
use Log::Any::Adapter::Callback 0.09;
use Log::Any::Adapter;

our ( $method, $format );
Log::Any::Adapter->set(
    'Callback',
    min_level  => 'trace',
    logging_cb => sub {
        ( $method, undef, $format ) = @_;
    },
    detection_cb => sub {
        $method = shift;
    }
);

1
```
Of course, if you are familiar with `Log::Any` you are more then welcome to send a PR for this. Thanks!

**Comment by ezimuel** [comment]
Closing this since not relevant anymore.
