### ISSUE TITLE
META.json: missing repository + bugtracker information 

### ISSUE THREAD

**Issue by eserte** [elastic/elasticsearch-perl#203]
It seems that the 7.711 release is missing the repository and bugtracker information in META.json. This means that https://metacpan.org/release/Search-Elasticsearch has no link to the gitgub page, and the issues link points to rt.cpan.org, which is probably wrong.

This information available was in the 7.30 release:
https://metacpan.org/diff/file?target=EZIMUEL/Search-Elasticsearch-7.711/&source=EZIMUEL%2FSearch-Elasticsearch-7.30#META.json

**Comment by oalders** [comment]
#204 would fix this.

**Comment by ezimuel** [comment]
Thanks @eserte amd @oalders. I'll fix this with a patch release `7.11.1`.

**Comment by ezimuel** [comment]
Fixed with [7.11.1](https://github.com/elastic/elasticsearch-perl/releases/tag/version_7.711001) patch release.
