### ISSUE TITLE
ILM remove_lifecycle seems to be missing?

### ISSUE THREAD

**Issue by Euromancer** [elastic/elasticsearch-perl#210]
Hi
Im trying to use remove_lifecycle but im getting: 
Can't locate object method "remove_lifecycle" via package "Search::Elasticsearch::Client::7_0::Direct::ILM"

**Comment by ezimuel** [comment]
@Euromancer I think you are refering to `ilm.remove_policy` API. We need to update the documentation for `Ilm` namespace [here](https://github.com/elastic/elasticsearch-perl/blob/7.x/lib/Search/Elasticsearch/Client/7_0/Direct/ILM.pm#L146-L152).

**Comment by ezimuel** [comment]
Finally, I released [8.0.0](https://github.com/elastic/elasticsearch-perl/releases/tag/version_8.00) updated and tested using Elasticsearch 8.5.3. I also updated the docs with an [Elastic Cloud connection example](https://www.elastic.co/guide/en/elasticsearch/client/perl-api/master/_elastic_cloud.html)
