### ISSUE TITLE
Please verify SSL server identity by default

### ISSUE THREAD

**Issue by fschlich** [elastic/elasticsearch-perl#211]
I'm forwarding Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954111

The reporter notes that _Your package uses the Perl module HTTP::Tiny, but it does not force
the verify_SSL attribute to a true value. ... I believe that the encryption of a transmission has no value when
talking to the wrong person._

While you document in Search::Elasticsearch::Cxn::HTTPTiny how to turn on remote host verification, would you consider switching the default to always verify https connections (and perhaps giving your user the option to turn verification back off should this really be needed)?

**Comment by ezimuel** [comment]
This has been fixed in HTTP-Tiny ver. [0.083](https://metacpan.org/dist/HTTP-Tiny/changes#L19)
