### ISSUE TITLE
Update documentation to contain all client methods / API endpoints

### ISSUE THREAD

**Issue by darxriggs** [elastic/elasticsearch-perl#215]
The client has been updated in [API.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Role/API.pm) to reflect changes in the Elasticsearch API.

What is missing is the documentation.

According to the changes in `API.pm` (up to 7.15.1) these files seem to require an update:
- [AsyncSearch.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/AsyncSearch.pm)
- [Autoscaling.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Autoscaling.pm)
- [Cat.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Cat.pm)
- [CCR.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/CCR.pm)
- [Cluster.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Cluster.pm)
- [DanglingIndices.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/DanglingIndices.pm)
- [DataFrameTransformDeprecated.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/DataFrameTransformDeprecated.pm)
- [Enrich.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Enrich.pm)
- [Eql.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Eql.pm)
- [Features.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Features.pm)
- [Fleet.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Fleet.pm)
- [ILM.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/ILM.pm)
- [Indices.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Indices.pm)
- [Ingest.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Ingest.pm)
- [Logstash.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Logstash.pm)
- [ML.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/ML.pm)
- [Nodes.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Nodes.pm)
- [Rollup.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Rollup.pm)
- [SearchableSnapshots.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/SearchableSnapshots.pm)
- [Security.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Security.pm)
- [Shutdown.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Shutdown.pm)
- [Slm.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Slm.pm)
- [Snapshot.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Snapshot.pm)
- [SQL.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/SQL.pm)
- [TextStructure.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/TextStructure.pm)
- [Transform.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Transform.pm)
- [Watcher.pm](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Client/7_0/Direct/Watcher.pm)

**Comment by ezimuel** [comment]
@darxriggs thanks for the PR, yes you right we need to update all the documentation for the endpoints. I'm trying to automate this since now Elasticsearch exposes about 400 endpoints and it's quite difficult to update everything manually.
