### ISSUE TITLE
End-of-Life announcement for version 8

### ISSUE THREAD

**Issue by ezimuel** [elastic/elasticsearch-perl#220]
We want to announce end-of-life for version `8` of [elastic/elaticsearch-perl](https://github.com/elastic/elasticsearch-perl) software. This announcement marks the final milestone of the lifecycle management phase of the `8.x` release family. This means `8.x` will be the last major version supported by [Elastic](https://www.elastic.co/).
Moreover, in `8.x` we are going to update only the API endpoints providing also bug and security fixes.

**Comment by fy2** [comment]
@ezimuel , you will stop supporting Perl for ES after `8`?

What kind of strategy would you recommend for those who depend on ES Perl client libs currently?

Are there any plans by some other "entity" (that you are aware of) to continue maintain/create ES Perl client libs?

**Comment by technige** [comment]
@fy2 Yes, unfortunately we will discontinue the client for Perl after the 8.x series and will not be able to offer general perl support. The only exception will be for users with existing support contracts, which we will continue to honour.

This is not a decision we have made lightly, but given the steadily diminishing size of the perl user base, it no longer makes sense for us to provide an official client for that language.

We are hopeful that a community maintainer will step forward to carry on development. Any such party should get in touch with us to discuss the details.

**Comment by ezimuel** [comment]
@fy2  I'll document the steps needed to update the project with the Elasticsearch API endpoints. In this way a community member can easily fork the project and continue to support it. If anyone is interested, we can even arrange a meeting/presentation to share these information.

**Comment by fy2** [comment]
Thank you @ezimuel and @technige .

I would be very interested to join the meeting/presentation to see if I can somehow contribute/help to the future development.

**Comment by ezimuel** [comment]
Finally, I released [8.0.0](https://github.com/elastic/elasticsearch-perl/releases/tag/version_8.00) updated and tested using Elasticsearch 8.5.3. I also updated the docs with an [Elastic Cloud connection example](https://www.elastic.co/guide/en/elasticsearch/client/perl-api/master/_elastic_cloud.html)

**Comment by minusdavid** [comment]
> [@fy2](https://github.com/fy2) I'll document the steps needed to update the project with the Elasticsearch API endpoints. In this way a community member can easily fork the project and continue to support it. If anyone is interested, we can even arrange a meeting/presentation to share these information.

@ezimuel Thanks for that. Where can we find that documentation? As you can see in the above commits here, Koha - a growing open source Perl system - is an increasingly heavy user of Search::Elasticsearch, so it would be great to have access to that information.
