### ISSUE TITLE
There is no $bulk->add_actions() method

### ISSUE THREAD

**Issue by warewolf** [elastic/elasticsearch-perl#223]
I'm not at the right PC right now with the right SSH key to make a proper PR, sorry!

https://github.com/elastic/elasticsearch-perl/blob/master/lib/Search/Elasticsearch/Client/7_0/Bulk.pm#L303

```
    $bulk->add_action($_) for (@actions);

# or

    foreach my $action (@actions) {
      $bulk->add_action($action);
    }
```

might be a better piece of example code.

**Comment by ezimuel** [comment]
@warewolf what do you mean by there is not `add_actions()`? I see it [here](https://github.com/elastic/elasticsearch-perl/blob/master/lib/Search/Elasticsearch/Client/7_0/Bulk.pm#L28).

**Comment by warewolf** [comment]
@ezimuel notice how I said "add_actions()" and linked to the POD documentation?

**Comment by ezimuel** [comment]
@warewolf thanks, I fixed it [here](https://github.com/elastic/elasticsearch-perl/commit/5ba9768c02fb4ac2e31f323eadacd601e46508e1). Sorry for the misunderstanding, I didn't see the `s`.
