### ISSUE TITLE
MetaCPAN can't be queried because of missing header

### ISSUE THREAD

**Issue by oalders** [elastic/elasticsearch-perl#228]
As a point of interest, I tried to run a command line script to query MetaCPAN earlier today and I came across this error:

> [ProductCheck] ** The client noticed that the server is not Elasticsearch and we do not support this unknown product, called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at scripts/file/3-find-files-in-top-level-by-name.pl line 11

MetaCPAN has been a thin wrapper around Elasticsearch for ~12 years. I guess the commit in question is ec7810a18eed46f. We could add a `X-Elastic-Product` header to the API output, but I'm not sure if that is acceptable under Elastic's TOS. We are still running Elasticsearch 2.4.

I guess we could also have users pin to an earlier version of the client, but adding the header would be the simplest approach for end users.

**Comment by ezimuel** [comment]
@oalders did you solve the issue with the suggested constrain? Let me know, thanks.

**Comment by oalders** [comment]
@ezimuel I haven't dealt with it yet, but at least we have some options. Thanks for your quick follow-up on this.
