### ISSUE TITLE
Why no Future support?

### ISSUE THREAD

**Issue by shadowcat-mst** [elastic/elasticsearch-perl#30]
The Moo community and assorted people have been working with Future.pm for building highly parallel code for some time, and it's proven a pragmatic API that's basically 'Promises without the bureaucracy and pointless CS posturing'.

While I understand the desire to support multiple event loops, Future.pm is already built to do so and has been in production for us for longer than the Promises module has been on CPAN.

I'd much prefer to use tried and tested code - is there any chance of allowing support for doing so as well as using the super-abstract API of Promises for people wanting javascript compatibility?

**Comment by clintongormley** [comment]
Inactive, closing
