### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by faxm0dem** [elastic/elasticsearch-perl#45]
The following code seems to leak memory pretty fast when looking at RSS consumption (30MB in 10 seconds): `perl -MESLeak -le 'init(); while (true) {queue({foo=>"bar"}); }; deinit(); done'`

``` perl
#!/usr/bin/perl

package ESLeak;

use warnings;
use strict;
use Search::Elasticsearch;

my $es;
my $bulk;
my %default;

BEGIN {
    %default = (
        index => "index",
        type => "type",
        max_count => 256,
        nodes => [
            "localhost:9200",
        ],
    );
}

use vars qw(@ISA @EXPORT);
@ISA = qw(Exporter);
@EXPORT = qw/init queue deinit/;

sub init {
    $es = Search::Elasticsearch -> new(
        nodes => $default{nodes},
        cxn_pool => 'Sniff',
    );

    $bulk = $es -> bulk_helper(
        index => $default{index},
        type => $default{type},
        max_count => $default{max_count},
    );
}

sub queue {
    my ($input) = @_;

    $bulk -> index(
        { index => "foo", type => "bar", source => $input }
    );
}

sub deinit {
    $bulk -> flush
}
```

**Comment by pasfreelance** [comment]
Hi,

@faxm0dem re-opened this issue after a short chat on IRC.

My Memory is running full by indexing ~14,000,000 Documents on my Dev box. After the box crashed i started to do a short analyze.

Here is my Analyze Script using Memory::Usage:

https://gist.github.com/pasfreelance/8f6273243eed61f19ff4

I am running this Script on a Gentoo Linux running Perl v5.20.1 with Version 2.00 of Search::Elasticsearch from CPAN.

I can add my Report, but it is kind of big (41MB)

If i can provide more needed informations or can do support for fixing that issue, just leave me a note here please.

**Comment by clintongormley** [comment]
Hi @pasfreelance 

I'm on OSX so Memory::Usage doesn't work, but when i run your script I reach a stable state very quickly and it doesn't move from there.

If you could make the report (zipped?) available somewhere, it may shed some light.

btw, recreating the bulk helper every thousand docs doesn't make any sense.  Your script could be rewritten as follows:

    my $test_record = {
        foo => "bar",
        bar => "baz"
    };

    my $bulk = $es->bulk_helper(
      index     => 'test', 
      type      => 'test_items', 
      max_count => 1000
    );

    for ( 1 .. 100_000 ) {
      $bulk->index({source=>$test_record});
    }

    $bulk->flush;

**Comment by pasfreelance** [comment]
Hi,

here is my report file as .tgz

http://moveax.wtf/report.tgz

I did not implemented your changes yet. But i can give you an update after implementing those changes.

**Comment by pasfreelance** [comment]
My used Module versions can be found here:

https://gist.github.com/pasfreelance/8f6273243eed61f19ff4#file-used_versions

**Comment by pasfreelance** [comment]
Hey,

i have implemented your changes in my Testscript. An updated Report can be found here:

http://moveax.wtf/report_after_changes.tgz

I updated the test script in my gist, so you can see what i am doing:

https://gist.github.com/pasfreelance/8f6273243eed61f19ff4#file-test-pl

**Comment by clintongormley** [comment]
The memory leak is coming from Sub::Name < 0.08
See https://metacpan.org/changes/distribution/Sub-Name#L27)

Opened an issue in Moo to specify a min required version: https://rt.cpan.org/Ticket/Display.html?id=109139

Will leave this open and specify a min version of Moo once a new version has been released.

**Comment by pasfreelance** [comment]
Thanks for your Support, after upgrading Sub::Name i don't have problems anymore

**Comment by faxm0dem** [comment]
thanks a lot for tracking this down @clintongormley
