### ISSUE TITLE
time based flushing for bulk API

### ISSUE THREAD

**Issue by abraxxa** [elastic/elasticsearch-perl#59]
It would be great if you could configure a time based auto-flushing instead or in addition to the current max_count and max_size.

**Comment by bbailey1024** [comment]
While that might be a decent option, the functionality is easy enough to accomplish outside of the bulk api.

Something like this works for us.

```perl
my $watch_interval = 15; # Flush every 15 seconds
my $startTime = time();

#doStuff

if ((time() - $startTime) > $watch_interval) {
		$bulk->flush();
		$startTime = time();
}
```

**Comment by abraxxa** [comment]
I'm looking for a way to flush say every second in our Message::Passing daemons that store messages in ES.
I guess I could add a code like your example to https://metacpan.org/source/ABRAXXA/Message-Passing-Output-Search-Elasticsearch-0.002/lib/Message/Passing/Output/Search/Elasticsearch.pm#L68 but if it's possible or planned directly in Search::Elasticsearch I'd prefer that.

**Comment by clintongormley** [comment]
Hi @abraxxa 

I've been travelling for the last month. This should be easy enough to add to the Bulk helper.  The only issue is that the interface currently doesn't care which event library you use, but timers would be library specific (eg using AnyEvent or Mojo)

**Comment by clintongormley** [comment]
(you need a timer rather than just an if loop in case not many messages are flowing)

**Comment by clintongormley** [comment]
In the end I didn't add a timer (eg with AE::timer) because that would make the modules backend dependent.  However, every time a new item is added to the queue, the last flush time is checked

**Comment by abraxxa** [comment]
Great, thank you very much!
