### ISSUE TITLE
Pod::Simple as a configure-requires prereq?

### ISSUE THREAD

**Issue by karenetheridge** [elastic/elasticsearch-perl#62]
Why is Pod::Simple a configure-requires prereq? I don't see any code in Makefile.PL that uses it, and the commit that added it (044947eeaa) isn't specific what the problem was.

**Comment by clintongormley** [comment]
I added it as a workaround for something which broke upstream.  Not sure who changed what but suddenly all my builds were red.

**Comment by clintongormley** [comment]
Closed by 752d83010a84074b7c5d31f12e0cbd65e56a71cf
