### ISSUE TITLE
Bulk buffer being flushed on NoNodes?

### ISSUE THREAD

**Issue by heathtechnical** [elastic/elasticsearch-perl#63]
I'm seeing my bulk buffer being flushed on a NoNodes exception, is this expected behavior or have I missed something obvious?

$ ./bbtest.pl
_buffer_count=1
[NoNodes] ** No nodes are available: [http://nowhere:9200], called from sub Search::Elasticsearch::Transport::try {...}  at Try/Tiny.pm line 81.
_buffer_count=0

**Comment by clintongormley** [comment]
Hi @heathtechnical 

Could you upload your test script please?

**Comment by heathtechnical** [comment]
Yep, sure.

    use strict;
    use warnings;
    
    use Search::Elasticsearch;
    
    my $es = Search::Elasticsearch->new(nodes => [ "http://nowhere:9200" ]);
    my $es_bulk = $es->bulk_helper();
    
    $es_bulk->index({ index => "testing123", type => "test", source => { this => "that" } });
    
    print "_buffer_count=".$es_bulk->_buffer_count."\n";
    eval {$es_bulk->flush() } || print "$@\n";
    print "_buffer_count=".$es_bulk->_buffer_count."\n";

**Comment by clintongormley** [comment]
thanks @heathtechnical - fixed, will be in the next release
