### ISSUE TITLE
detect_noop should work with bulk update

### ISSUE THREAD

**Issue by sewi-cpan** [elastic/elasticsearch-perl#65]
#6822 introduced the detect_noop option for the Update API. It should be supported in the Bulk API, too.
#10881 turned out that ElasticSearch already supports it, but the Perl client doesn't.

**Comment by clintongormley** [comment]
thanks for opening

**Comment by sewi-cpan** [comment]
Created pull request: https://github.com/elastic/elasticsearch-perl/pull/66
