### ISSUE TITLE
Replicating odd cpantesters failure

### ISSUE THREAD

**Issue by singingfish** [elastic/elasticsearch-perl#69]
I'm seeing a test failure on my development box that is identical to [this failure](http://www.cpantesters.org/cpan/report/49d0dd4c-fd7d-11e4-bd65-233de0bfc7aa) on cpantesters (well we're on perl 5.18.1 and an older linux kernel).  I've been through that failure, and compared it  with a success and checked the cpan modules are not too outdated compared to each other etc.  but I'm still none the wiser as to what's going on.  Any ideas?

**Comment by clintongormley** [comment]
That's very odd.  I'm using `127.0.0.2:9200` as an IP address which is not supposed to exist (see https://github.com/elastic/elasticsearch-perl/blob/master/t/70_Helper/45_bulk_cxn_errors.t#L11).

Could you run that test as follows please:

    TRACE=1 prove -v -l t/70_Helper/45_bulk_cxn_errors.t

**Comment by singingfish** [comment]
$ TRACE=1 prove -v -l t/70_Helper/45_bulk_cxn_errors.t
    t/70_Helper/45_bulk_cxn_errors.t .. 
    ok 1 - Buffer count pre-flush
    # Request to: http://127.0.0.2:9200
    curl -XPOST 'http://localhost:9200/foo/bar/_bulk?pretty=1' -d '
    {"create":{}}
    {"foo":"bar"}
    '
    
    not ok 2 - threw Search::Elasticsearch::Error::NoNodes
    not ok 3 - Buffer count post-flush
    1..3
    # Response: 200, Took: 162 ms
    # {
    #    "items" : [
    #       {
    #          "create" : {
    #             "_index" : "foo",
    #             "_version" : 1,
    #             "_type" : "bar",
    #             "status" : 201,
    #             "_id" : "AU3nLknq7h9Oh5-VezQO"
    #          }
    #       }
    #    ],
    #    "errors" : false,
    #    "took" : 144
    # }
    
    
    #   Failed test 'threw Search::Elasticsearch::Error::NoNodes'
    #   at t/70_Helper/45_bulk_cxn_errors.t line 31.
    # expecting: Search::Elasticsearch::Error::NoNodes
    # found: normal exit
    
    #   Failed test 'Buffer count post-flush'
    #   at t/70_Helper/45_bulk_cxn_errors.t line 32.
    #          got: '0'
    #     expected: '1'
    # Looks like you failed 2 tests of 3.
    Dubious, test returned 2 (wstat 512, 0x200)
    Failed 2/3 subtests 
    
    Test Summary Report
    -------------------
    t/70_Helper/45_bulk_cxn_errors.t (Wstat: 512 Tests: 3 Failed: 2)
      Failed tests:  2-3
      Non-zero exit status: 2
    Files=1, Tests=3,  1 wallclock secs ( 0.03 usr  0.01 sys +  0.28 cusr  0.03     csys =  0.35 CPU)

**Comment by singingfish** [comment]
Although I did a bit of (dist::zilla) installing/upgrading of some cpan modules on the box that it originally failed on today, and that particular box did the following afterwards which was a bit odd:

    $ TRACE=1 prove -v -l t/70_Helper/45_bulk_cxn_errors.t
    t/70_Helper/45_bulk_cxn_errors.t .. 
    ok 1 # skip IO::Socket::IP doesn't respect timeout: https://rt.cpan.org/Ticket/Display.html?id=103878
    ok 2 # skip IO::Socket::IP doesn't respect timeout: https://rt.cpan.org/Ticket/Display.html?id=103878
    ok 3 # skip IO::Socket::IP doesn't respect timeout: https://rt.cpan.org/Ticket/Display.html?id=103878
    1..3 
    ok
    All tests successful.

**Comment by clintongormley** [comment]
OK - you upgraded to perl 5.20, and IO::Socket::IP doesn't respect the timeout parameter and just hangs for 30 seconds or something until it fails to connect, which is why that test is skipped.  

From the first trace output you give, it looks like Elasticsearch has bound to 127.0.0.2:9200, which is why the bulk request accidentally succeeded.

If you try this command you should get a response:

    curl 127.0.0.2:9200/

I need an IP address which doesn't work.  Could you try this as well?

    curl 127.0.0.3:9200/

(or variations of the this to find IP addresses which don't respond :) )

**Comment by singingfish** [comment]
Looking at the output of this, those all seem to exist.  I've asked my sysadmin to elaborate.

    for i in {1..255}; do curl -s 127.0.0.$i:9200 || echo No response ; done | less

**Comment by singingfish** [comment]
OK, it's an elasticsearch configuration problem. Changed host from 0.0.0.0 in the config to being 127.0.0.1 and the test passes.

**Comment by clintongormley** [comment]
I think it's just a linux vs osx thing.  Would you mind trying (eg) 127.1.1.1 (with the previous settings that you had)?

**Comment by singingfish** [comment]
Nah, the loopback device is assigned the entire 127 class A block. god knows why.  e.g. curl 127.254.34.96:9200

**Comment by singingfish** [comment]
Yeah seems like it's a linux thing from the early days of TCP/IP

**Comment by clintongormley** [comment]
@singingfish would you mind trying again using this IP address: 10.255.255.1:9200

From what I've read this should work...

**Comment by singingfish** [comment]
looking good:

    $ curl 10.255.255.1:9200
    curl: (7) couldn't connect to host

**Comment by clintongormley** [comment]
sweet. thanks for testing.

Closed by d65396da42e4bf72b9606c7e835f8420ecb13058

**Comment by yahermann** [comment]
Hi there, may I humbly request a simplification of the resolution, for us newbies? :-)
1. Unable to install Search::Elasticsearch, tests fail as discussed above
2. Set network.bind_host to 127.0.0.1 in elasticsearch.yml
3. Restart elasticsearch
4. Installed Search::Elasticsearch successfully (tests passed)
5. Then what?  Remove network.bind_host and accept default?

**Comment by clintongormley** [comment]
thanks @yahermann 

i'll be doing a new release pretty soon, which will incorporate the commit above.  should resolve things just fine.
