### ISSUE TITLE
Avoid dedicated master nodes

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch-perl#71]
As far as I can see, with a simple demo and running a standard config Elasticsearch, and one with:

``` yaml
node.master: true
node.data: false
```

the perl client will still send indexing requests to the dedicated master. Shouldn't this be avoided? [This blog post](https://www.elastic.co/blog/resiliency-elasticsearch) says "By reducing the amount of resource intensive work that these nodes do (no data ingestion or search), we greatly reduce the chance of cluster instability.". The python client seems to avoid dedicated masters.

**Comment by ezimuel** [comment]
Solved in #73.
