### ISSUE TITLE
Make node sniffer more selective

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch-perl#73]
Add support for:

```
sniff_node_types: {
    data:   "yes | no | fallback",
    master: "yes | no | fallback",
    client: "yes | no | fallback"
}

prefer_nodes: "192.168.*|rack:one|etc"
```

Closes #71

**Comment by darxriggs** [comment]
This was closed without a comment. Does this mean it will not be implemented?

At least the [default implementation](https://github.com/elastic/elasticsearch-perl/blob/version_7.715/lib/Search/Elasticsearch/Role/CxnPool/Sniff.pm#L102) of `should_accept_node` still accepts every node in v7.715.
