### ISSUE TITLE
build prereqs should be in test

### ISSUE THREAD

**Issue by karenetheridge** [elastic/elasticsearch-perl#75]
I'm looking at this dist because it's being assigned for the PR Challenge.. this would make for an easy quick fix...

Test::More should be a test prereq, not build.  Dist::Zilla's generated Makefile.PL already takes care of the backwards compatibility issues for older EUMM not supporting test prereqs -- the proper thing to do in Dist::Zilla-based dists is to declare prereqs completely and correctly, and it will take care of the fiddly stuff.

**Comment by karenetheridge** [comment]
additonally, there's no need to make Pod::Simple a configure requirement, as it's not used at configure time (i.e. by Makefile.PL).

**Comment by clintongormley** [comment]
So the reason I added it was that installation was failing, because something was missing Pod::Simple - this was a long time ago so i forget the details. I think I had to make sure it was installed before EUMM, otherwise things went wrong, hence where it ended up.

no idea what has happened since.

**Comment by karenetheridge** [comment]
If you see it again, feel free to ping the toolchain gang and we'll be on it like a sack of potatoes :)

**Comment by clintongormley** [comment]
@karenetheridge while talking about toolchain issues, I'm no longer doing CI testing on 5.8 because of this bug: https://rt.cpan.org/Ticket/Display.html?id=105524

Getting that resolved would be awesome.

**Comment by karenetheridge** [comment]
08:42 <@ether> Clinton Gormley tells me that he can't test elasticsearch on 5.8 because of this issue in Test::Harness -- https://rt.cpan.org/Ticket/Display.html?id=105524
08:51 <@rjbs> huh
08:53 <@rjbs> ether: Using current prove?
08:53 <@rjbs> App::Prove on my system loads modules before harness.  I realize that's not solving the whole thing, but sadly it rules out the simplest possibility.

**Comment by clintongormley** [comment]
@karenetheridge I've tracked it down to a bug in v2.13 of base.pm, see https://rt.cpan.org/Ticket/Display.html?id=105524#txn-1514009
