### ISSUE TITLE
Information for how to build the distribution should be added to the CONTRIBUTING file

### ISSUE THREAD

**Issue by shlomif** [elastic/elasticsearch-perl#76]
Hi all!

Currently, it is not clear how to build and test the distribution. "dzil test" does not work and "dzil build" yields a tree without a Makefile.PL or a Build.PL. We've discussed it on Freenode's #perl channel and concluded it was not trivial.

So please add this information to the CONTRIBUTING file.

( I gained interest in this distribution, because I was assigned it as part of the CPAN Pull Request Challenge).

— @shlomif

**Comment by clintongormley** [comment]
Hi @shlomif 

There are three packages in this repo: the main Search-Elasticsearch, Search-Elasticsearch-Async, and Search-Elasticsearch-Cxn-NetCurl

The dist.ini for each package is located in the dist/, dist-async/ and dist-netcurl/ directories.  All you have to do is cd into the relevant directory and run the dzil commands from there

want to send a PR?

**Comment by shlomif** [comment]
OK, I'm having further problems now trying to build the distribution that is found inside the "./dist/" dir:

```
shlomif@telaviv1:~/Download/unpack/perl/cpan/TO_DEL/elasticsearch-perl/dist$ git st
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
shlomif@telaviv1:~/Download/unpack/perl/cpan/TO_DEL/elasticsearch-perl/dist$ git remote -v
origin  git@github.com:shlomif/elasticsearch-perl.git (fetch)
origin  git@github.com:shlomif/elasticsearch-perl.git (push)
upstream        git@github.com:elastic/elasticsearch-perl.git (fetch)
upstream        git@github.com:elastic/elasticsearch-perl.git (push)
shlomif@telaviv1:~/Download/unpack/perl/cpan/TO_DEL/elasticsearch-perl/dist$ dzil test --all
[DZ] building distribution under .build/hPNyvfZwI7 for installation
[DZ] beginning to build Search-Elasticsearch
[DZ] guessing dist's main_module is lib/Search/Elasticsearch.pm
[VersionFromModule] dist version 1.20 (from lib/Search/Elasticsearch.pm)
[PkgVersion] skipping lib/Search/Elasticsearch.pm: assigns to $VERSION
[GitHub::Meta] Getting GitHub repository info
[ExtraTests] rewriting release test xt/release/pod-syntax.t
[ExtraTests] rewriting author test xt/author/no-tabs.t
[ExtraTests] rewriting author test xt/author/eol.t
Error open (<) on 'lib/Search/Elasticsearch.pm': No such file or directory at /usr/lib/perl5/vendor_perl/5.22.0/Pod/Readme/Filter.pm line 86.
shlomif@telaviv1:~/Download/unpack/perl/cpan/TO_DEL/elasticsearch-perl/dist$ 

```

Can anyone possibly shed any light on what to do?

Regards,

— @shlomif

**Comment by clintongormley** [comment]
Hmmm no idea.  I'm upgrading all my local modules to see if it reproduces.

**Comment by shlomif** [comment]
@clintongormley : thanks for your effort!

**Comment by clintongormley** [comment]
Hmm, just updated to perl 5.22 and now I'm getting the same exception :(

**Comment by shlomif** [comment]
@clintongormley : I see! Thanks for the update. For the record, I am getting the same exception with a perlbrew-installed perl-5.22.0.

**Comment by clintongormley** [comment]
OK - it seems to be caused by this bug in Dist::Zilla::Plugin::ReadmeFromPod: https://rt.cpan.org/Ticket/Display.html?id=100820

you can force downgrade that module with:

    cpanm Dist::Zilla::Plugin::ReadmeFromPod@0.21 Test::Pod

Also, update from master - i've pushed a couple of minor fixes

**Comment by shlomif** [comment]
@clintongormley : sorry for the late response. After thinking about it, I decided that I'll opt to not contribute to Search-Elasticsearch until this problem is fixed. Part of the risk of using Dist-Zilla with many potentially-problematic plugins is that you deter potential contributors. It's really sad.
