### ISSUE TITLE
Scroll doesn't play well with forking

### ISSUE THREAD

**Issue by jeteve** [elastic/elasticsearch-perl#79]
Hi,

Here's a problem to consider:
  
    my $scroll = ...;
    while (my $doc = $scroll->next) {
        # fork to do something and wait for your forked process to finish.
    }

## Problem:

Search::Elasticsearch::Role::Scroll will DEMOLISH itself in the forked process, rendering the top parent process's scroll object invalid.

## Proposed solution:

In Search::Elasticsearch::Role::Scroll::DEMOLISH, do finish ONLY if the current process is the same as the process that started the scroll.

This implies that Search::Elasticsearch::Scroll has to remember the pid at build time.

**Comment by clintongormley** [comment]
Hi @jeteve 

Why would you fork after starting a scroll?  Scrolling is a serial process only - you can't split a scroll request over multiple workers. Instead, you can run multiple scroll requests with filters (eg filter on a timestamp field, so that one scroll request gets everything in 2010, another in 2011, etc)

**Comment by jeteve** [comment]
@clintongormle The example code I've given is just to illustrate the issue. If you want to know more, I can tell you that we fork because we use MCE to do stuff in parrallel on chunks of data.

Anyway, that might be a right or wrong approach according to anyone's taste. This is not the point here. This an issue that needs to be fixed to make this piece of software more robust when silly people like me use it in a way that was not intended.

I gather for your answer that you have got nothing against my proposed solution, so if it's still ok,
I'm happy to fix it myself and send you guys a pull request.

**Comment by clintongormley** [comment]
Hi @jeteve 

Ah I've just reread your description and now actually understand it - apologies.  Reopening.

**Comment by jeteve** [comment]
Thanks @clintongormley! So is it ok if I send a fix?

**Comment by clintongormley** [comment]
@jeteve a PR would be great.  Actually, what I'd also like is to throw an exception if you try to use a scroll request from a process with a different PID, ie to stop people trying to share a scroll request over a fork.

**Comment by jeteve** [comment]
Yup, good idea.
