### ISSUE TITLE
Issues using templates

### ISSUE THREAD

**Issue by setuk** [elastic/elasticsearch-perl#82]
Just getting to grips with ES and the perl module so this may be a newbie misunderstanding.

Passing in a valid connection and a valid string into this sub

```
my $result = &getNames($connection, 'someName');

sub getNames($connection, $name){

	my $e = shift;
	my $name = shift;


	$results = $e->render_search_template(
	    template => {
	        query => {
	            match => {
	                "{{my_field}}" => "{{my_value}}"
	            }
	        },
	        size => "{{my_size}}"
	    },
	    params => {
	        my_field => 'FullName2',
	        my_value => $name,
	        my_size  => 5
	    }
	);
return $results;

}
```

Throwing this error:-

```
[Param] ** Unknown param (template) in (render_search_template) request. See docs at: http://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html, called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at ./getr2.pl line 130.Simons-MacBook-Pro:elastic simon$
```

I get the impression from the doc that i should be able to define the template inline and the code should interpolate the variables and execute the query.
Is this correct or do i need to preload the template and reference it by name.
Please clarify - thanks in advance.

Simon

**Comment by clintongormley** [comment]
Hi @setuk 

The docs were incorrect, thanks for spotting.  The way to use render_search_template (only available in ES 2.0 and above) is:

    $results = $e->render_search_template(
        body => {
          inline => {
              query => {
                  match => {
                      "{{my_field}}" => "{{my_value}}"
                  }
              },
              size => "{{my_size}}"
          },
          params => {
              my_field => 'FullName2',
              my_value => $name,
              my_size  => 5
          }
        }
    );

**Comment by setuk** [comment]
Cool.
search_template work the same way?

**Comment by setuk** [comment]
nevermind - it does :-)
Good job on the API - some undertaking that must have been. Its awesome.
