### ISSUE TITLE
Load time v.s. instantiation time bug in S::E::Role::Scroll

### ISSUE THREAD

**Issue by warewolf** [elastic/elasticsearch-perl#90]
commit cc2ec29c0a9d6272b87121639b6cec2bf308bd37 introduces a Load time v.s. instantiation time bug where no code that forks at all can ever scroll.

(thanks go to @shadowcat-mst for helping me confirm my suspicion that it was a load time v.s. instantiation time bug + helping understand Moo a little more -- btw he suggests you review all your 'has' statements for similar bugs/situations now)

https://github.com/elastic/elasticsearch-perl/commit/cc2ec29c0a9d6272b87121639b6cec2bf308bd37#diff-bd7ac5c086b118688d3f2e2eb2b6fcd7R21 should be 

`has '_pid'          => ( is => 'ro', default => sub { $$ } );`

**Comment by clintongormley** [comment]
thanks for reporting @warewolf
